use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use cargo_metadata::{DependencyKind, MetadataCommand};

use crate::error::{Error, Result};

/// Extracted workspace dependency graph containing only internal (workspace) dependencies.
#[derive(Debug)]
pub struct WorkspaceGraph {
    /// Names of all workspace member crates.
    pub members: BTreeSet<String>,
    /// For each workspace member, the set of internal dependencies (crate names).
    pub dependencies: BTreeMap<String, BTreeSet<String>>,
}

impl WorkspaceGraph {
    /// Build the workspace graph by running `cargo metadata`.
    ///
    /// If `manifest_path` is provided, it is passed to `cargo metadata --manifest-path`.
    /// If `check_dev_deps` is false, dev-dependencies are excluded from the graph.
    pub fn from_metadata(manifest_path: Option<&Path>, check_dev_deps: bool) -> Result<Self> {
        let mut cmd = MetadataCommand::new();
        if let Some(path) = manifest_path {
            cmd.manifest_path(path);
        }

        let metadata = cmd.exec().map_err(|source| Error::Metadata { source })?;
        let resolve = metadata.resolve.ok_or(Error::NoResolve)?;

        // Build set of workspace member package IDs for filtering.
        let workspace_member_ids: BTreeSet<_> =
            metadata.workspace_members.iter().cloned().collect();

        // Build name lookup: package ID -> crate name (for workspace members only).
        let id_to_name: BTreeMap<_, _> = metadata
            .packages
            .iter()
            .filter(|pkg| workspace_member_ids.contains(&pkg.id))
            .map(|pkg| (pkg.id.clone(), pkg.name.clone()))
            .collect();

        let members: BTreeSet<String> = id_to_name.values().cloned().collect();

        // For each workspace member node in the resolve graph, collect internal deps.
        let mut dependencies: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();

        for node in &resolve.nodes {
            let Some(member_name) = id_to_name.get(&node.id) else {
                continue; // Not a workspace member.
            };

            let mut internal_deps = BTreeSet::new();
            for dep in &node.deps {
                // Skip non-workspace dependencies.
                let Some(dep_name) = id_to_name.get(&dep.pkg) else {
                    continue;
                };

                // Filter by dependency kind if check_dev_deps is false.
                if !check_dev_deps {
                    let has_normal_or_build = dep.dep_kinds.iter().any(|dk| {
                        matches!(dk.kind, DependencyKind::Normal | DependencyKind::Build)
                    });
                    if !has_normal_or_build {
                        continue;
                    }
                }

                internal_deps.insert(dep_name.clone());
            }

            dependencies.insert(member_name.clone(), internal_deps);
        }

        // Ensure every member has an entry (even if it has zero internal deps).
        for name in &members {
            dependencies.entry(name.clone()).or_default();
        }

        Ok(Self {
            members,
            dependencies,
        })
    }
}

/// Generate a baseline `depgraph-rules.toml` config from a workspace graph.
///
/// Crates are sorted topologically (leaves first, most-dependent last).
/// Dependency lists are sorted alphabetically within each crate's entry.
pub fn generate_config(graph: &WorkspaceGraph) -> String {
    let mut output = String::new();
    output.push_str("# depgraph-rules.toml\n");
    output.push_str("# Generated by: cargo depgraph-check generate\n");
    output.push_str("# This config reflects the current workspace dependency graph.\n");
    output.push_str("# Edit to tighten rules — remove dependencies you want to forbid.\n\n");
    output.push_str("[rules]\n");
    output.push_str("# Crates are sorted by dependency depth (leaves first).\n\n");

    // Compute depth for topological sort.
    let depths = compute_depths(&graph.dependencies);
    let mut sorted_crates: Vec<_> = graph.members.iter().collect();
    sorted_crates.sort_by(|a, b| {
        let da = depths.get(a.as_str()).copied().unwrap_or(0);
        let db = depths.get(b.as_str()).copied().unwrap_or(0);
        da.cmp(&db).then_with(|| a.cmp(b))
    });

    for name in &sorted_crates {
        let deps = graph.dependencies.get(name.as_str());
        let mut dep_list: Vec<&str> = deps
            .map(|d| d.iter().map(String::as_str).collect())
            .unwrap_or_default();
        dep_list.sort();

        if dep_list.is_empty() {
            output.push_str("# No internal dependencies\n");
            output.push_str(&format!("{name} = []\n\n"));
        } else {
            let deps_str = dep_list
                .iter()
                .map(|d| format!("\"{d}\""))
                .collect::<Vec<_>>()
                .join(", ");
            output.push_str(&format!("# Depends on: {}\n", dep_list.join(", ")));
            output.push_str(&format!("{name} = [{deps_str}]\n\n"));
        }
    }

    output.push_str(
        "[options]\nstrict = true\ncheck_dev_deps = false\nunmatched_config_entries = \"warn\"\n",
    );

    output
}

/// Compute the dependency depth for each crate.
/// Leaf crates (no deps) have depth 0, their dependents have depth 1, etc.
fn compute_depths(deps: &BTreeMap<String, BTreeSet<String>>) -> BTreeMap<&str, usize> {
    let mut depths: BTreeMap<&str, usize> = BTreeMap::new();

    // Simple iterative approach: keep computing until stable.
    let mut changed = true;
    while changed {
        changed = false;
        for (name, dep_set) in deps {
            let max_dep_depth = dep_set
                .iter()
                .filter_map(|d| depths.get(d.as_str()).copied())
                .max()
                .unwrap_or(0);

            let new_depth = if dep_set.is_empty() {
                0
            } else {
                max_dep_depth + 1
            };

            let current = depths.get(name.as_str()).copied().unwrap_or(0);
            if new_depth > current {
                depths.insert(name.as_str(), new_depth);
                changed = true;
            }
        }
    }

    depths
}
